import { Platform, StyleSheet } from "react-native";
import Constants from "expo-constants";
import Colors from "../../../global/Colors";
import { responsiveHeight } from "react-native-responsive-dimensions";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 0,
    paddingRight: 0,
  },
  overlayWrap: {
    backgroundColor: Colors.black,
    height: "100%",
    width: "100%",
    display: "flex",
  },
  topHeader: {
    display: 'flex',
    alignItems: Platform.OS === 'ios' ? 'flex-end' : 'flex-end',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 20,
    paddingRight: 20,
    height: Constants.statusBarHeight + (Platform.OS === 'ios' ? responsiveHeight(10) : 70),
    paddingBottom: Platform.OS === 'ios' ? 10 : 20,
    width: '100%',
  },


  titleHolder: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
  },
  backWrap: {
    // borderColor: 'red',
    // borderWidth: 1,
    // borderStyle: 'solid',
    display: "flex",
    justifyContent: "center",
    height: 24,
    width: 24,
    marginRight: 5,
  },
  backArrow: {
    height: 14,
    width: 8,
  },
  pageHeading: {
    fontSize: 22,
    color: Colors.white,
    textTransform: "capitalize",
    fontWeight: "300",
  },
  fileIco: {
    display: "flex",
    justifyContent: "center",
    height: 24,
    width: 24,
    marginRight: 5,
  },
  filteBtn: {
    height: 21,
    width: 21,
  },
  overlayWrapBanner: {
    height: 310,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "nowrap",
    flexDirection: "row",
    marginBottom: 50,
  },
  textWrap: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    paddingLeft: 20,
  },
  bannerText: {
    color: Colors.white,
    position: "relative",
    zIndex: 1,
    // borderColor:'red',
    // borderWidth:1,
    // borderStyle:'solid',
    fontSize: 36,
    fontWeight: "300",
    fontFamily: "Montserrat-Regular",
    position: "relative",
    zIndex: 1,
    width: 282,
    marginBottom: 15,
  },
  captionText: {
    fontSize: 14,
    color: Colors.iron,
    fontWeight: "300",
    width: 162,
  },
  bannerBG: {
    flex: 1,
    position: "absolute",
    right: 20,
    bottom: 20,
  },
  productList: {
    paddingLeft: 20,
    paddingRight: 20,
    marginBottom: 100,
  },
  productListVerical: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  productCardSmall: {
    paddingBottom: 0,
  },
  hotDealsWrap: {
    paddingLeft: 20,
    paddingRight: 20,
    marginBottom: 20,
  },
  headingCategory: {
    fontSize: 22,
    color: Colors.white,
    textTransform: "capitalize",
    fontWeight: "500",
    marginBottom: 20,
  },
  hotDealsSlide: {
    margin: 0,
    padding: 0,
    display: "flex",
    // justifyContent: 'space-between',
    flexDirection: "row",
    marginBottom: 20,
    // height:200,
  },
  productCard: {
    borderStyle: "solid",
    borderRadius: 20,
    width: 320,
    marginRight: 10,
    backgroundColor: Colors.deep_cove,
    flex: 1,
    //paddingBottom: 25,
    borderColor: Colors.torea_bay,
    borderWidth: 1,
    shadowColor: Colors.catalina_blue,
    shadowOffset: { width: 3, height: 5 },
    shadowOpacity: 0.6,
    shadowRadius: 5,
    elevation: 5,
    height: 425,
  },
  categoryTagWrap: {
    backgroundColor: Colors.denim,
    height: 25,
    borderRadius: 25,
    position: "absolute",
    left: 11,
    top: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 10,
    paddingRight: 10,
    zIndex: 1,
  },
  categoryTag: {
    fontSize: 11,
    color: Colors.white,
    textTransform: "uppercase",
  },
  productWrap: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 0,
    marginBottom: 20,
    height: 191,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: "hidden",
  },
  productWrapSmall: {
    width: 100,
  },
  productDetails: {
    paddingLeft: 16,
    paddingRight: 16,
    flex: 1,
    paddingBottom: 25,
    paddingTop: 25,
    display: "flex",
    justifyContent: "flex-end",
  },
  productTitle: {
    fontSize: 18,
    color: Colors.white,
    marginBottom: 10,
    flexWrap: "wrap",
    display: "flex",
    width: "100%",
    fontFamily: "Montserrat-SemiBold",
  },
  productDetailsInner: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  productDetailsInnerSmall: {
    // justifyContent: 'space-between',
  },
  productModel: {
    fontSize: 14,
    color: Colors.white,
    fontFamily: "Montserrat-Regular",
  },
  productReating: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 10,
  },
  starRating: {
    marginRight: 5,
    height: 10,
    width: 10,
  },
  reviews: {
    fontSize: 14,
    color: Colors.white,
    fontFamily: "Montserrat-Regular",
  },
  lensType: {
    backgroundColor: Colors.jordy_blue,
    height: 25,
    borderRadius: 25,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 10,
    paddingRight: 10,
    marginRight: 15,
  },
  priceWrap: {
    justifyContent: 'space-between',
    alignItems: "flex-end",
    // marginTop:responsiveHeight(6)

  },
  priceTag: {
    fontSize: 14,
    color: Colors.white,
    marginBottom: 10,
    fontFamily: "Montserrat-Regular",
  },
  price: {
    fontSize: 16,
    color: Colors.white,
    fontFamily: "Montserrat-Regular",
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid'
  },
  salePrice: {
    fontSize: 22,
    color: Colors.white,
  },
  moreProductsWrap: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 80,
  },
  moreProducts: {
    fontSize: 16,
    color: Colors.azure_radiance,
    textTransform: "capitalize",
    fontWeight: "700",
  },
  catalogBanner: {
    display: "flex",
    flexDirection: "column",
  },
  bannerMainWrap: {
    display: "flex",
  },

  captionText: {
    fontSize: 14,
    color: Colors.white,
    fontWeight: "500",
    fontFamily: "Montserrat-Regular",
    width: 182,
  },
  bannerBg: {
    flex: 1,
    position: "absolute",
    right: 20,
    bottom: 20,
    height: 255,
    width: 255,
  },
  bannerWrap: {
    flexDirection: "row",
    // paddingLeft: 28,
    // paddingRight: 28,
  },
  // bannerTextWrap: {
  //     flexDirection: 'column',
  //     display: 'flex',
  //     justifyContent: 'center',
  //     alignItems: 'center',
  // },

  bannerNavWrap: {
    position: "absolute",
    zIndex: 2,
    bottom: 0,
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },

  bannerNav: {
    width: 6,
    height: 6,
    borderRadius: 10,
    marginLeft: 3,
    marginRight: 3,
  },

  productImg: {
    height: 190,
    width: 94,
  },

  productImgSmall: {
    height: "100%",
    width: "100%",
    resizeMode: "contain",
  },
  hotDealsList: {
    paddingLeft: 15,
    paddingRight: 15,
  },
  productCardSingle: {
    height: "auto",
    width: "100%",
    marginRight: 0,
    alignItems: "center",
    paddingBottom: 0,
    paddingTop: 0,
  },

  productWrapSingle: {
    paddingLeft: 10,
    paddingRight: 10,
    marginBottom: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 105,
    height: 170,
    // backgroundColor:'#fff',
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 20,
  },

  productDetailsSingle: {
    paddingLeft: 16,
    paddingRight: 16,
    flex: 1,
    paddingBottom: 0,
    paddingTop: 0,
  },

  textCompatiableMount: {
    fontSize: 14,
    color: Colors.white,
    fontFamily: "Montserrat-Regular",
  },
  textProductModel: {
    width: 120,
    fontSize: 14,
    color: Colors.white,
    fontFamily: "Montserrat-Regular",
  },

  mainScroll: {
    height: "100%",
  },
  textCard: {
    marginLeft: 5,
    fontSize: 14,
    color: Colors.white,
    fontWeight: "600",
    lineHeight: 17,
    fontFamily: "Montserrat-SemiBold",
    textAlign: "center",
  },
  certificateWrap: {
    width: 167,
    height: 40,
    borderRadius: 30,
    paddingLeft: 25,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(5, 23, 71, 0.9)",
    borderColor: "rgba(7, 31, 95, 1)",
    borderWidth: 1,
    borderStyle: "solid",
    marginBottom: 18,
    marginRight: 10
  },
  newsCardWrap: {
    marginBottom: Platform.OS === 'ios' ? 110 : 110,
  },
  statusView: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: Colors.cornflower_blue,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  statusText: {
    color: '#ffffff',
    fontSize: 12,
  },
});
